image: Visual Studio 2015

environment:
  global:
    PYTHON: "C:\\Python36"

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}

build_script:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - pip install --user tox
  - pip install --user virtualenv
  - pip install --user requests
  - python appveyor.py
  - python venv.py
  - copy "%PYTHON%\\python3.dll" "venv\\Scripts"
  - venv\\Scripts\\pip install https://github.com/pyinstaller/pyinstaller/archive/964547cd92cabe28150d52c2ca809de74a5ddbaa.zip
  - venv\\Scripts\\python pinsis.py --qtifw
  - move ..\\*.exe .

artifacts:
  - path: '*.exe'

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
