image: Visual Studio 2015

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}

build_script:
  - git config --global advice.detachedHead false
  - git clone https://github.com/altendky/st sub/epyqlib
  - ps: try { git -C sub/epyqlib checkout $(git ls-tree ${Env:APPVEYOR_REPO_BRANCH}:sub | python -c 'import sys; line = sys.stdin.readline(); print(line.split()[2])') 2>&1 } catch {}
  - c:\\python36\\python venv.py
  - copy c:\\python36\\python3.dll venv\\Scripts
  - venv\\Scripts\\python pinsis.py

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
